### ISSUE TITLE
It is impossible to use FeatureToggles.IsEnabled("FeatureName") in Global.asax.cs Application_Start()

### ISSUE THREAD

**Issue by Antonytm** [aqueduct/Aqueduct.Toggles#4] opened 2016-07-12 13:09 UTC
**Stack Trace:**
[HttpException (0x80004005): Request is not available in this context]
   System.Web.HttpContext.get_Request() +12004632
   System.Web.HttpContextWrapper.get_Request() +35
   Aqueduct.Toggles.Overrides.CookieOverrideProvider.GetOverrides() in C:\Projects\Aqueduct.Toggles\Aqueduct.Toggles\Overrides\CookieOverrideProvider.cs:31
   Aqueduct.Toggles.FeatureConfiguration.IsEnabled(String name) in C:\Projects\Aqueduct.Toggles\Aqueduct.Toggles\FeatureConfiguration.cs:30

**Comment by marto83** [comment] 2016-07-12 15:30
We are going to get that fixed in the next release. The issue is the default override provider is based on cookies and it errors as there is no request context. 
You have 2 options:
1. Update the CookieOverrideProvider to add a null check for Request
2. Implement an empty override provider (IOverrideProvider) and pass it to `FeatureToggles.SetOverrideProvider(emptyOverrideProvider)`

There is a PR that will fix this issue and hope to get it merge in the next few days.

**Comment by neilduncan** [comment] 2016-09-12 15:57
This should work now. Thanks @Antonytm for raising it, and @marto83 for fixing it :+1:

**Closed by neilduncan** 2016-09-12 15:57 UTC
